---
# tasks file for ansible-role-kale/


# AD authentication

- name: Install Kerberos and sssd-clients
  yum: name={{ item }} state=present
  with_items:
    - adcli
    - sssd-krb5
    - sssd-ad
    - sssd-ldap
    - sssd-common-pac
    - krb5-workstation


# krb5.conf
- name: Configure Kerberos integration with AD
  template: backup=yes src=krb5.conf.j2 dest=/etc/krb5.conf
            owner=root group=root mode=0644

# ldap
- name: Configure ldap integration with AD
  template: backup=yes src=ldap.conf.j2 dest=/etc/openldap/ldap.conf
            owner=root group=root mode=0644

# nsswitch
- name: Configure nsswitch integration with AD
  template: backup=yes src=nsswitch.conf.j2 dest=/etc/nsswitch.conf
            owner=root group=root mode=0644

# sssd
- name: Configure sssd integration with AD
  template: backup=yes src=sssd.conf.j2 dest=/etc/sssd/sssd.conf
            owner=root group=root mode=0600
  notify: restart_sssd




# pam sshd
- name: Configure pam sshd integration with AD
  template: backup=yes src=sshd.j2 dest=/etc/pam.d/sshd
            owner=root group=root mode=0644


# Add AD domains hosts 
- name: cleanning previous entries on /etc/hosts
  lineinfile: backup=yes dest=/etc/hosts regexp="^.*\b(ForestDnsZones)\b.*$" line="{{ ad_hosts }}" state=absent
  when: ad_hosts is defined

- name: populate /etc/hosts file with AD hosts
  lineinfile: dest=/etc/hosts line="{{ ad_hosts }}" state=present
  when: ad_hosts is defined

- name: cleanning blank lines on /etc/hosts
  lineinfile: backup=no dest=/etc/hosts regexp="^\s*$" state=absent
  when: ad_hosts is defined



# user creation with pam module

- name: copy user creation script
  template: backup=yes src=aduser.sh.j2 dest={{ pamexec_script }} owner=root group=root mode=0755

- name: sssd enabled and running
  service:
    name: "{{ sssd_service }}"
    enabled: true
    state: running



